= 时区

== 术语
* GMT 格林威治时间，所有时区都以和GMT之间的偏移量做为参考
** Mon Feb 13 08:00:00 GMT+00:00 2012 = Mon Feb 13 08:00:00 GMT+08:00 2012
* UTC 协调世界时，Z为0时区的标志
** 时区偏移表示
*** ±[hh]:[mm]
*** ±[hh][mm]
*** ±[hh]
** 2018-05-20 09:30:00 UTC = 2018-05-20 09:30:00z = 2018-05-20 17:30:00 +8000
* epoch = 1970-01-01 00:00:00 UTC

[%hardbreaks]
GMT和UTC是两种不同的时间标准，目前大部分使用的都是UTC，GMT逐渐被淘汰。
我们常说的UTC时区指的是UTC0时区，例如2018-05-20 09:30:00 UTC。

== java
=== date类型
Date类型不包含时区信息，存的是从epoch以来过去的毫秒，而epoch是UTC时间。所以也可以说Date类型的存储使用的是UTC时区。

=== calendar类型
带时区信息

=== 时区与格式化
[%hardbreaks]
我们看到的时间都是经过格式化后的字符串，时区是格式化（序列化和反序列化）函数需要关心的事情，而不是存储关心的，同一个date按不同的时区格式化就会看到不一样的时间，但是存储的是同一个值。
SimpleDateFormat默认使用jvm的时区（操作系统时区）打印时间，也可以显式设置时区。

=== 序列化和反序列化
[%hardbreaks]
把字符串解析为date时需要明确时区，或者时间字符串的格式就是带时区信息的例如：
yyyy-MM-dd'T'HH:mm:ssZ  => 2021-01-14T17:16:11 +0800。
jackson解析时如果不做任何配置，时间格式必须是yyyy-MM-dd'T'HH:mm:ssZ 或者yyyy-MM-dd'T'HH:mm:ss.SSSZ，其中Z代表时区，但是可以省略
如果没有时区，默认是UTC，即0时区，而不是jvm的时区，所以一定注意json序列化时如果字符串不带时区，一定要全局规范使用UTC。
jackson中objectMapper.setDateFormat(new SimplDateFormat("yyyy-MM-dd HH:mm:ss"));这样设置的话会使用jvm的时区，这样就依赖于部署的机器需要有固定的时区。
可以采用下面两种方法使用固定时区：

[%hardbreaks]
* DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); +
  format.setTimeZone(TimeZone.getTimeZone("UTC")); +
  objectMapper.setDateFormat(format);
* objectMapper.setTimeZone(TimeZone.getTimeZone("UTC"));

=== mysql
[%hardbreaks]
查看时区设置
SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;

通过jdbcurl强制使用指定的时区：xx?serverTimezone=UTC

[%hardbreaks]
mysql存储的datetime值和java的date差不多，都不含时区信息，jdbc在读取数据库中的值后使用指定的时区把值解析为java的date，和jackson把字符串反序列化date是类似的。
所以应用程序需要保证写入时和读取时使用的时区是一样的。如果url中不指定时区，则数据库的时区不能随意修改，修改了之后应用程序读取的时间就会错误。
我们可以理解为jdbc写入数据时按照指定的时区把java的date转化为了字符串存入数据库，jdbc读取是再按照指定的时区把数据库的值反序列化为java的date。
这个指定的时区就是mysql数据库设置的时区，按照优先级从高到低： +
url中serverTimezone参数 > session.time_zone > global.time_zone

[%hardbreaks]
举个例子：
jdbcurl = localhost:3306?serverTimezone=UTC
执行sql: insert into table(t) values('2020-01-02 00:00:00');
mysql存储：存储为2020-01-02 00:00:00
jdbc读取：Date t = rs.getTimestamp("t");
从数据库把2020-01-02 00:00:00传输给jdbc客户端
jdbc客户端使用calendar接收2020-01-02 00:00:00，并把时区设置为UTC
DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
System.out.println(format.format(t));
输出结果: 如果jvm的时区是UTC，输出为2020-01-02 00:00:00，如果jvm的时区是GMT+8，输出是2020-01-02 00:08:00
通过jdbc写入数据时，jvm的时区是什么没有任何影响的，应用程序只需要保证写入和读取使用相同的数据库时区。

=== 毫秒
[%hardbreaks]
目前mysql5.6及以上都支持datetime和timestamp增加毫秒数，例如： 
insert into table(t) values('2020-01-02 00:00:00.90')
但是低版本的都不支持毫秒，所以不能把内存中的date和从数据库中取出来的时间进行比较。